version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-dev-container
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mount entire project directory to sync changes
      - /app/node_modules  # Ensure node_modules is not overwritten
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
